version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - '1337:1337'
    volumes:
      - './src:/app'
      - '/app/node_modules'
    environment:
      NODE_ENV: development
