version: '3.4'
services:
  app:
    image: strapi/strapi
    volumes:
      - ./src:/srv/app
    ports:
      - 1337:1337
      - 9229:9229
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_HOST: database
      DATABASE_PORT: 27017
      DATABASE_NAME: app
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: secret
    command: npm --node-options --inspect=0.0.0.0:9229 run develop
  database:
    image: mongo
    volumes:
      - '/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: secret
